# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site. Don't let it end in '/' or you'll mess the links up
url: "http://giant-pepper.cloudvent.net"

# Build settings
markdown: kramdown

#Handling Reading
encoding: "utf-8"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

paginate: 4
permalink: none

gems:
  - jemoji
  - octopress-autoprefixer
  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-seo-tag

# Excludes
exclude:
  - .sass-cache

sass:
  sass_dir: _sass
  style: :nested
