
#for the navbar links.
custom_links:
  - title: Marketing Plan
    url: http://realestateprg.com/our-marketing/
  - title: Our Listings
    url: http://realestateprg.com/listings/  

#site settings
title: Silicon Valley Real Estate Video Blog
description: Learn all the tips, tricks and more for buyers and sellers in the San Jose Area Real Estate Market

#controls all the site info
client:
  market: San Jose
  name: #
  brand: PRG Real Estate
  brokerage: #
  address: '1590 Oakland Rd #B104 <br>
San Jose, CA 95131'
  phone: 408-416-2488
  email: info@realestatePRG.com
  url: http://RealEstatePRG.com
  # if forms put '/homevalue/' or '/homesearch/'
  homeeval: 'http://www.texthomevalue.com'
  homesearch: 'http://www.buysellprg.com/'
  VR_form: http://oi.vresp.com?fid=0d42af93c9

# social links
socials:
  facebook: 'https://www.facebook.com/ParamountRealtyGroup/'
  linkedin: 'https://www.linkedin.com/company/paramount-realty-group'
  gplus: '#'
  youtube: 'https://www.youtube.com/channel/UCMiC_NieOuhzi3qNys7x6Kw'
  twitter: 'https://twitter.com/PRGEnrique'
  instagram: '#'
  pinterest: '#'
  zillow: 'http://www.zillow.com/profile/TEAM-PRG/'
  trulia: '#'
  yelp: '#'
  podcast: 'https://itunes.apple.com/us/podcast/enrique-medellin-real-estate/id1075193302?mt=2'

#podcast settings
podcast:
  title: PRG Real Estate Podcast
  categories:
    - category: 'News &amp; Politics'
  image: 'http://i.imgur.com/DUtCRwl.png'
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Jose Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Durwin Homes Group - your professional San Jose Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Jose, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Enrique Medellin

#layout options
review_sm_icons: false
audit_header: false

#image settings
images:
  hero_image_path: /img/enriquevideoblogbg-blur.jpg
  hero_logo_path: /img/PRG-Logo.png
  hero_background_hex: '#2f7283'
  client_headshot_path: /img/medellin_headshot.jpg

#colors
brand_hex: "#2f7283"
fontcolor_hex: "#252525"
