
#for the navbar links.
custom_links:
  - title: Luxury Properties
    url: http://www.sflivingspace.com/luxury-properties/

#site settings
title: San Francisco Real Estate Video Blog
description: Beats, Rhymths, life

#controls all the site info
client:
  market: San Francisco
  name: Durwin Cheung
  brand: Distinctive Collection
  brokerage: Better Homes and Gardens
  address: '1 Daniel Burnham Court #260C <br>
San Francisco, CA 94109'
  phone: 1-415-867-2369
  email: bryce@getvyral.com
  url: http://www.sflivingspace.com
  # if forms put '/homevalue/' or '/homesearch/'
  homeeval: '/homevalue/'
  homesearch: '/homesearch/'
  VR_form: http://oi.vresp.com?fid=cf8d350165

# social links
socials:
  facebook: 'https://www.facebook.com/DurwinHomes/'
  linkedin: 'https://www.linkedin.com/in/durwincheung'
  gplus: 'http://plus.google.com/106120372813474502294'
  youtube: 'https://www.youtube.com/channel/UC9ZidMCfhkwVx_G2bemRqxg'
  twitter: 'https://twitter.com/DurwinCheungSF'
  instagram: '#'
  pinterest: '#'
  zillow: 'http://www.zillow.com/profile/durwincheung/'
  trulia: 'http://www.trulia.com/profile/durwin-cheung-agent-san-francisco-ca-zgss3vz1/overview'
  yelp: '#'
  podcast: 'https://itunes.apple.com/us/podcast/san-francisco-real-estate/id1094796993?mt=2'

#podcast settings
podcast:
  title: San Francisco Real Estate Podcast
  categories:
    - category: 'News &amp; Politics'
  image: 'http://i.imgur.com/jJxfq9v.jpg'
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Francisco Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Durwin Homes Group - your professional San Francisco Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Durwin Cheung

#layout options
review_sm_icons: false
audit_header: false

#image settings
images:
  hero_image_path: /img/sf_downtown.jpg
  hero_logo_path: /img/Durwin_logo_white.png
  hero_background_hex: '#2F3544'
  client_headshot_path: /img/durwin_headshot.png
